name: Codecov

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Code coverage  
      uses: codecov/codecov-action@v1
