name: Codecov

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Code coverage  
      uses: codecov/codecov-action@v1
      with:
          directory: ./coverage/*.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
