name: JuanitaTests

on:
  push:
    branches: [main]
    paths:
      - "./**"
      - "!**.md"
  pull_request:
    branches: [main]
    paths:
      - "./**"
      - "!**.md"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - name: Cache node modules
        id: cacheStep
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: frontend-client/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: npm install

      - name: Builds
        run: npm run build --if-present

      - name: Tests
        run: npm test
